#!/usr/bin/env bash
# Lee outputs de Terraform y los volca a .env.infra (auto-generado).
# El Taskfile carga .env.infra via dotenv -> NO mas copy/paste.
source "$(dirname "$0")/_common.sh"

ENV_FILE="$(pwd)/.env.infra"

# Helper que tolera outputs faltantes (e.g., si infra aun no esta aplicada)
get_output() {
  local key="$1"
  ( cd infra && terraform output -raw "$key" 2>/dev/null ) || echo ""
}

log "leyendo terraform outputs..."

S3_BUCKET=$(get_output s3_bucket)
AWS_REGION_VAL=$(get_output aws_region_used)
TRAINING_HOST=$(get_output training_eip)
MLFLOW_HOST=$(get_output mlflow_eip)
MLFLOW_URL=$(get_output mlflow_url)
LAMBDA_POWER_NAME=$(get_output power_lambda_name)
SSH_KEY=$(get_output ssh_private_key_path)

if [ -z "$S3_BUCKET" ] || [ -z "$TRAINING_HOST" ]; then
  die "outputs vacios. Corriste 'task infra:apply' primero?"
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by 'task infra:env-export' on $(date)
# DO NOT EDIT - re-run el task para refrescar tras infra:apply
AWS_REGION=$AWS_REGION_VAL
S3_BUCKET=$S3_BUCKET
TRAINING_HOST=$TRAINING_HOST
MLFLOW_HOST=$MLFLOW_HOST
MLFLOW_TRACKING_URI=$MLFLOW_URL
LAMBDA_POWER_NAME=$LAMBDA_POWER_NAME
SSH_KEY=$SSH_KEY
EOF

log "escrito -> $ENV_FILE"
log "contenido:"
sed 's/^/  /' "$ENV_FILE"
log "El Taskfile lo cargara automaticamente en la proxima ejecucion."
